# Generated by Django 6.0.5 on 2026-06-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='manga_image',
            field=models.ImageField(blank=True, null=True, upload_to='manga/'),
        ),
    ]
